services:
  - type: web
    name: chatbot-gpt-wa
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: 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
      - key: D360_API_KEY
        value: cfBAd3_sandbox
